Metrics/BlockLength:
  Max: 150
Layout/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 60
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/ClassLength:
  Max: 250
Metrics/ParameterLists:
  Max: 10
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.x
Bundler/OrderedGems:
  Enabled: false
Documentation:
  Enabled: false